#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""Repo-time sync tool for the `_shared/` vendored helpers.

Skills cannot `import` each other (they must stay independently installable), so
shared code is **vendored** — committed copies regenerated from a canonical
`_shared/` source, never hand-maintained. This tool regenerates every copy
in-place from canonical, in two modes:

* **region** — a marker-fenced REGION inside a canonical file is copied into a
  matching marker-fenced region of each consumer (the consumer is a *larger* file
  that embeds the shared snippet). Marker lines are preserved (a consumer's
  "generated by" banner may differ from canonical by design); only the interior
  between the markers is overwritten. Used for the active-set classifier
  (`active_set.py`) and the defensive `--json` extractor (`json_extract.py`).
* **whole-file** — a canonical file is copied VERBATIM (byte-for-byte) to each
  consumer path (the consumer *is* the shared file — a standalone runnable
  script). A 100%-shared file carries no in-band markers; every copy is
  byte-identical to canonical. Used for `manifest_update.py`.

Usage:

    uv run _shared/sync.py            # regenerate every consumer in-place
    uv run _shared/sync.py --check    # report-only: exit 1 if any consumer diverges (CI/manual)

Policed by DRIFT-CHECK.md `value-equal` edges (`e-active-set-copy-*`,
`e-json-extract-copy-*`, `e-manifest-update-copy-*`); `--check` is the CI/manual
backstop for the same divergence.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# Repo root = parent of this file's dir (_shared/).
REPO_ROOT = Path(__file__).resolve().parent.parent


class RegionError(ValueError):
    """A file is missing the region markers, or they are garbled/duplicated/out-of-order."""


@dataclass
class RegionAsset:
    """A canonical marker-fenced region vendored into larger consumer files."""

    name: str
    canonical: Path
    begin: str  # substring/stem matched on the BEGIN marker line
    end: str  # substring/stem matched on the END marker line
    consumers: list[Path]

    @property
    def begin_re(self) -> re.Pattern:
        return re.compile(re.escape(self.begin))

    @property
    def end_re(self) -> re.Pattern:
        return re.compile(re.escape(self.end))


@dataclass
class WholeFileAsset:
    """A canonical file copied verbatim (byte-for-byte) to each consumer path."""

    name: str
    canonical: Path
    consumers: list[Path]


def _skill(*parts: str) -> Path:
    return REPO_ROOT.joinpath("skills", *parts)


REGION_ASSETS = [
    RegionAsset(
        name="active-set classifier",
        canonical=REPO_ROOT / "_shared" / "active_set.py",
        begin=">>> BEGIN active-set classifier",
        end="<<< END active-set classifier",
        consumers=[
            _skill("yf-beads-hygiene", "scripts", "beads_hygiene.py"),
            _skill("yf-beads-upstream", "scripts", "upstream.py"),
        ],
    ),
    RegionAsset(
        name="defensive json extractor",
        canonical=REPO_ROOT / "_shared" / "json_extract.py",
        begin=">>> BEGIN defensive json extractor",
        end="<<< END defensive json extractor",
        consumers=[
            _skill("yf-plan", "scripts", "plan_manager.py"),
            _skill("yf-research", "scripts", "research_manager.py"),
        ],
    ),
]

WHOLE_FILE_ASSETS = [
    WholeFileAsset(
        name="manifest_update.py",
        canonical=REPO_ROOT / "_shared" / "manifest_update.py",
        consumers=[
            _skill("yf-beads-upstream", "scripts", "manifest_update.py"),
            _skill("yf-optimal-instructions", "scripts", "manifest_update.py"),
            _skill("yf-plan", "scripts", "manifest_update.py"),
            _skill("yf-research", "scripts", "manifest_update.py"),
            _skill("yf-skill-authoring", "scripts", "manifest_update.py"),
        ],
    ),
]


def extract_region(text: str, begin_re: re.Pattern, end_re: re.Pattern) -> str:
    """Return the interior body (lines strictly between the BEGIN and END marker lines).

    Raises RegionError if the markers are absent, duplicated, or out of order. The returned
    body excludes the marker lines themselves and includes the interior verbatim.
    """
    lines = text.splitlines(keepends=True)
    begins = [i for i, ln in enumerate(lines) if begin_re.search(ln)]
    ends = [i for i, ln in enumerate(lines) if end_re.search(ln)]
    if len(begins) != 1 or len(ends) != 1:
        raise RegionError(
            f"expected exactly one BEGIN and one END marker, found "
            f"{len(begins)} BEGIN / {len(ends)} END"
        )
    b, e = begins[0], ends[0]
    if e <= b:
        raise RegionError("END marker precedes (or coincides with) BEGIN marker")
    return "".join(lines[b + 1 : e])


def replace_region(text: str, body: str, begin_re: re.Pattern, end_re: re.Pattern) -> str:
    """Return `text` with its region interior replaced by `body` (marker lines preserved)."""
    lines = text.splitlines(keepends=True)
    begins = [i for i, ln in enumerate(lines) if begin_re.search(ln)]
    ends = [i for i, ln in enumerate(lines) if end_re.search(ln)]
    if len(begins) != 1 or len(ends) != 1:
        raise RegionError(
            f"expected exactly one BEGIN and one END marker, found "
            f"{len(begins)} BEGIN / {len(ends)} END"
        )
    b, e = begins[0], ends[0]
    if e <= b:
        raise RegionError("END marker precedes (or coincides with) BEGIN marker")
    new_lines = lines[: b + 1] + [body] + lines[e:]
    return "".join(new_lines)


def canonical_region_body(asset: RegionAsset) -> str:
    """Extract the canonical region body from a RegionAsset's canonical file."""
    return extract_region(asset.canonical.read_text(), asset.begin_re, asset.end_re)


def sync_region_consumer(path: Path, asset: RegionAsset, body: str, *, check: bool) -> bool:
    """Sync (or check) one region consumer. Returns True if it diverged from canonical.

    Raises RegionError if the consumer's markers are absent/garbled.
    """
    text = path.read_text()
    current = extract_region(text, asset.begin_re, asset.end_re)
    if current == body:
        return False
    if not check:
        path.write_text(replace_region(text, body, asset.begin_re, asset.end_re))
    return True


def sync_whole_file_consumer(path: Path, body: str, *, check: bool) -> bool:
    """Sync (or check) one whole-file consumer. Returns True if it diverged from canonical."""
    current = path.read_text()
    if current == body:
        return False
    if not check:
        path.write_text(body)
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="report-only: do not write; exit 1 if any consumer diverges from canonical",
    )
    args = ap.parse_args(argv)

    diverged: list[str] = []
    errored: list[str] = []

    # ---- region-vendored assets ----
    for asset in REGION_ASSETS:
        try:
            body = canonical_region_body(asset)
        except FileNotFoundError:
            print(
                f"error: canonical missing: {asset.canonical.relative_to(REPO_ROOT)}",
                file=sys.stderr,
            )
            errored.append(str(asset.canonical))
            continue
        except RegionError as exc:
            print(
                f"error: canonical {asset.canonical.relative_to(REPO_ROOT)} "
                f"has no usable region: {exc}",
                file=sys.stderr,
            )
            errored.append(str(asset.canonical))
            continue
        for consumer in asset.consumers:
            rel = consumer.relative_to(REPO_ROOT)
            try:
                changed = sync_region_consumer(consumer, asset, body, check=args.check)
            except FileNotFoundError:
                print(f"error: consumer not found: {rel}", file=sys.stderr)
                errored.append(str(rel))
                continue
            except RegionError as exc:
                print(f"error: {rel}: {exc}", file=sys.stderr)
                errored.append(str(rel))
                continue
            _report(rel, changed, diverged, args.check)

    # ---- whole-file assets ----
    for asset in WHOLE_FILE_ASSETS:
        try:
            body = asset.canonical.read_text()
        except FileNotFoundError:
            print(
                f"error: canonical missing: {asset.canonical.relative_to(REPO_ROOT)}",
                file=sys.stderr,
            )
            errored.append(str(asset.canonical))
            continue
        for consumer in asset.consumers:
            rel = consumer.relative_to(REPO_ROOT)
            try:
                changed = sync_whole_file_consumer(consumer, body, check=args.check)
            except FileNotFoundError:
                print(f"error: consumer not found: {rel}", file=sys.stderr)
                errored.append(str(rel))
                continue
            _report(rel, changed, diverged, args.check)

    if errored:
        return 2
    if args.check and diverged:
        return 1
    return 0


def _report(rel: Path, changed: bool, diverged: list[str], check: bool) -> None:
    if changed:
        diverged.append(str(rel))
        verb = "DIVERGED" if check else "regenerated"
        print(f"{verb}: {rel}")
    else:
        print(f"in sync: {rel}")


if __name__ == "__main__":
    raise SystemExit(main())
