#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""Repo-time sync tool for the `_shared/` vendored active-set classifier (plan-014).

The active-set classifier is authored once in `_shared/active_set.py` and **vendored** —
as a committed, marker-fenced copy — into each consuming skill script (skills cannot
`import` each other; they must stay independently installable). This tool regenerates each
vendored region **in-place** from canonical, so the copies are *generated*, never
hand-maintained.

Usage:

    uv run _shared/sync.py            # regenerate every consumer's region in-place
    uv run _shared/sync.py --check    # report-only: exit 1 if any region diverges (CI/manual)

The canonical body is the text between the BEGIN/END markers in `_shared/active_set.py`.
Each consumer carries a matching marker-fenced region; this tool overwrites the interior of
that region with the canonical body, leaving the consumer's own marker lines intact (so the
"generated by" banner stays). No sibling `import`, no new file — each script stays
self-contained.

Policed by DRIFT-CHECK.md edges `e-active-set-copy-hygiene` / `e-active-set-copy-upstream`;
`--check` is the CI/manual backstop for the same divergence.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Repo root = parent of this file's dir (_shared/).
REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = REPO_ROOT / "_shared" / "active_set.py"

# The canonical→consumers map: which scripts carry a vendored copy of the region.
CONSUMERS = [
    REPO_ROOT / "skills" / "yf-beads-hygiene" / "scripts" / "beads_hygiene.py",
    REPO_ROOT / "skills" / "yf-beads-upstream" / "scripts" / "upstream.py",
]

# Markers are matched structurally (canonical vs consumer banners differ in wording but share
# the `BEGIN/END active-set classifier` stem), so the same extractor handles both.
BEGIN_RE = re.compile(r">>> BEGIN active-set classifier")
END_RE = re.compile(r"<<< END active-set classifier")


class RegionError(ValueError):
    """A file is missing the region markers, or they are garbled/duplicated/out-of-order."""


def extract_region(text: str) -> str:
    """Return the interior body (the lines strictly between the BEGIN and END marker lines).

    Raises RegionError if the markers are absent, duplicated, or out of order. The returned
    body excludes the marker lines themselves and includes the interior verbatim (with its
    trailing newline if any).
    """
    lines = text.splitlines(keepends=True)
    begins = [i for i, ln in enumerate(lines) if BEGIN_RE.search(ln)]
    ends = [i for i, ln in enumerate(lines) if END_RE.search(ln)]
    if len(begins) != 1 or len(ends) != 1:
        raise RegionError(
            f"expected exactly one BEGIN and one END marker, found "
            f"{len(begins)} BEGIN / {len(ends)} END"
        )
    b, e = begins[0], ends[0]
    if e <= b:
        raise RegionError("END marker precedes (or coincides with) BEGIN marker")
    return "".join(lines[b + 1 : e])


def replace_region(text: str, body: str) -> str:
    """Return `text` with its region interior replaced by `body` (marker lines preserved)."""
    lines = text.splitlines(keepends=True)
    begins = [i for i, ln in enumerate(lines) if BEGIN_RE.search(ln)]
    ends = [i for i, ln in enumerate(lines) if END_RE.search(ln)]
    if len(begins) != 1 or len(ends) != 1:
        raise RegionError(
            f"expected exactly one BEGIN and one END marker, found "
            f"{len(begins)} BEGIN / {len(ends)} END"
        )
    b, e = begins[0], ends[0]
    if e <= b:
        raise RegionError("END marker precedes (or coincides with) BEGIN marker")
    new_lines = lines[: b + 1] + [body] + lines[e:]
    return "".join(new_lines)


def canonical_body(canonical_path: Path = CANONICAL) -> str:
    """Extract the canonical region body from `_shared/active_set.py`."""
    return extract_region(canonical_path.read_text())


def sync_file(path: Path, body: str, *, check: bool) -> bool:
    """Sync (or check) one consumer.

    Returns True if the file's region diverged from canonical (in `check` mode, a divergence
    is reported; in write mode, the file was rewritten). Returns False if already in sync.
    Raises RegionError if the consumer's markers are absent/garbled.
    """
    text = path.read_text()
    current = extract_region(text)
    if current == body:
        return False
    if not check:
        path.write_text(replace_region(text, body))
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--check",
        action="store_true",
        help="report-only: do not write; exit 1 if any consumer region diverges from canonical",
    )
    args = ap.parse_args(argv)

    try:
        body = canonical_body()
    except RegionError as exc:
        print(f"error: canonical {CANONICAL} has no usable region: {exc}", file=sys.stderr)
        return 2

    diverged: list[str] = []
    errored: list[str] = []
    for consumer in CONSUMERS:
        rel = consumer.relative_to(REPO_ROOT)
        try:
            changed = sync_file(consumer, body, check=args.check)
        except FileNotFoundError:
            print(f"error: consumer not found: {rel}", file=sys.stderr)
            errored.append(str(rel))
            continue
        except RegionError as exc:
            print(f"error: {rel}: {exc}", file=sys.stderr)
            errored.append(str(rel))
            continue
        if changed:
            diverged.append(str(rel))
            verb = "DIVERGED" if args.check else "regenerated"
            print(f"{verb}: {rel}")
        else:
            print(f"in sync: {rel}")

    if errored:
        return 2
    if args.check and diverged:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
