# /// script
# requires-python = ">=3.9"
# ///
"""Tests for _shared/sync.py — the repo-time active-set vendoring sync tool.

Run:  uv run --with pytest python3 -m pytest test_sync.py -q

The pure region functions (extract_region / replace_region / canonical_body / sync_file)
are exercised against in-memory fixtures and tmp_path files — no live consumers needed.
The main() integration tests monkeypatch the module's CANONICAL/CONSUMERS globals to point
at temp files, so they never touch the real skill scripts.
"""
import importlib.util
import sys
from pathlib import Path

import pytest

_spec = importlib.util.spec_from_file_location("sync", Path(__file__).parent / "sync.py")
sync = importlib.util.module_from_spec(_spec)
sys.modules["sync"] = sync
_spec.loader.exec_module(sync)


CONSUMER_BEGIN = "# >>> BEGIN active-set classifier (generated by _shared/sync.py — do not edit) >>>"
CONSUMER_END = "# <<< END active-set classifier <<<"


def make_consumer(body: str, *, before="import os\n", after="\ndef tail():\n    pass\n") -> str:
    """Build a fake consumer script carrying the generated-by marker fence around `body`."""
    return f"{before}{CONSUMER_BEGIN}\n{body}{CONSUMER_END}\n{after}"


# --- canonical_body -----------------------------------------------------------

def test_canonical_body_extracts_real_classifier():
    body = sync.canonical_body()
    assert body.startswith("GATE_TYPE")
    assert "def classify_active" in body
    assert "class ActiveSetReport" in body


def test_canonical_body_custom_path(tmp_path):
    p = tmp_path / "canon.py"
    p.write_text("x\n# >>> BEGIN active-set classifier (canonical) >>>\nPAYLOAD = 1\n# <<< END active-set classifier (canonical) <<<\ny\n")
    assert sync.canonical_body(p) == "PAYLOAD = 1\n"


# --- extract_region / replace_region ------------------------------------------

def test_replace_then_extract_roundtrips():
    body = sync.canonical_body()
    text = make_consumer("STALE = 0\n")
    out = sync.replace_region(text, body)
    assert sync.extract_region(out) == body


def test_replace_preserves_surroundings_and_markers():
    body = "NEW = 1\n"
    text = make_consumer("OLD = 9\n")
    out = sync.replace_region(text, body)
    assert "import os" in out          # before
    assert "def tail" in out           # after
    assert CONSUMER_BEGIN in out       # generated-by marker retained
    assert CONSUMER_END in out
    assert "OLD = 9" not in out        # interior replaced
    assert "NEW = 1" in out


def test_generated_by_marker_present_after_replace():
    """The generated-by banner (not the canonical banner) must survive the sync."""
    out = sync.replace_region(make_consumer("OLD\n"), "X\n")
    assert "generated by _shared/sync.py" in out


# --- error cases: absent / garbled fences -------------------------------------

def test_missing_markers_raises():
    with pytest.raises(sync.RegionError):
        sync.extract_region("no markers anywhere here\n")


def test_only_begin_marker_raises():
    with pytest.raises(sync.RegionError):
        sync.extract_region(f"{CONSUMER_BEGIN}\nbody\n")


def test_out_of_order_markers_raise():
    bad = f"{CONSUMER_END}\nbody\n{CONSUMER_BEGIN}\n"
    with pytest.raises(sync.RegionError):
        sync.extract_region(bad)


def test_duplicate_markers_raise():
    dup = f"{CONSUMER_BEGIN}\na\n{CONSUMER_END}\n{CONSUMER_BEGIN}\nb\n{CONSUMER_END}\n"
    with pytest.raises(sync.RegionError):
        sync.extract_region(dup)


# --- sync_file: idempotency, tamper detection ---------------------------------

def test_sync_file_regenerates_then_idempotent(tmp_path):
    body = sync.canonical_body()
    p = tmp_path / "consumer.py"
    p.write_text(make_consumer("STALE = 0\n"))

    # First sync: diverged -> rewritten.
    assert sync.sync_file(p, body, check=False) is True
    assert sync.extract_region(p.read_text()) == body
    # Second sync: already in sync -> no change.
    assert sync.sync_file(p, body, check=False) is False


def test_check_detects_tampered_region(tmp_path):
    body = sync.canonical_body()
    p = tmp_path / "consumer.py"
    p.write_text(make_consumer(body))            # start in sync
    assert sync.sync_file(p, body, check=True) is False

    # Tamper the region.
    tampered = p.read_text().replace("def classify_active", "def classify_INACTIVE")
    p.write_text(tampered)
    assert sync.sync_file(p, body, check=True) is True   # divergence reported
    # check mode must NOT have rewritten the file.
    assert "classify_INACTIVE" in p.read_text()


def test_check_clean_after_sync(tmp_path):
    body = sync.canonical_body()
    p = tmp_path / "consumer.py"
    p.write_text(make_consumer("STALE\n"))
    sync.sync_file(p, body, check=False)
    assert sync.sync_file(p, body, check=True) is False


def test_sync_file_raises_on_unmarked_consumer(tmp_path):
    body = sync.canonical_body()
    p = tmp_path / "bare.py"
    p.write_text("import os\n# no region markers\n")
    with pytest.raises(sync.RegionError):
        sync.sync_file(p, body, check=False)


# --- main() integration (monkeypatched globals) -------------------------------

@pytest.fixture
def fake_repo(tmp_path, monkeypatch):
    canon = tmp_path / "active_set.py"
    canon.write_text(
        "# >>> BEGIN active-set classifier (canonical) >>>\nPAYLOAD = 42\n# <<< END active-set classifier (canonical) <<<\n"
    )
    c1 = tmp_path / "c1.py"
    c2 = tmp_path / "c2.py"
    c1.write_text(make_consumer("STALE1\n"))
    c2.write_text(make_consumer("STALE2\n"))
    monkeypatch.setattr(sync, "CANONICAL", canon)
    monkeypatch.setattr(sync, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(sync, "CONSUMERS", [c1, c2])
    return tmp_path, canon, c1, c2


def test_main_check_reports_divergence_exit_1(fake_repo, capsys):
    assert sync.main(["--check"]) == 1          # both stale -> diverged
    # check mode left files untouched
    _, _, c1, c2 = fake_repo
    assert "STALE1" in c1.read_text()
    assert "STALE2" in c2.read_text()


def test_main_write_then_check_clean(fake_repo):
    _, _, c1, c2 = fake_repo
    assert sync.main([]) == 0                    # regenerate both
    assert "PAYLOAD = 42" in c1.read_text()
    assert "PAYLOAD = 42" in c2.read_text()
    assert "STALE1" not in c1.read_text()
    assert sync.main(["--check"]) == 0           # now clean


def test_main_unmarked_consumer_exit_2(fake_repo):
    _, _, c1, _ = fake_repo
    c1.write_text("import os\n# no markers\n")
    assert sync.main(["--check"]) == 2           # RegionError -> error exit


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
