# /// script
# requires-python = ">=3.9"
# ///
"""Tests for _shared/sync.py — the repo-time `_shared/` vendoring sync tool.

Run:  uv run --with pytest python3 -m pytest test_sync.py -q

Covers both vendoring modes (plan-016):
  * region-vendored assets (active-set classifier, defensive json extractor) — a
    marker-fenced region copied into larger consumer files;
  * whole-file assets (manifest_update.py) — a canonical file copied verbatim.

The pure functions are exercised against in-memory fixtures and tmp_path files. The
main() integration tests monkeypatch the module's REGION_ASSETS / WHOLE_FILE_ASSETS /
REPO_ROOT to point at temp files, so they never touch the real skill scripts.
"""
import importlib.util
import re
import sys
from pathlib import Path

import pytest

_spec = importlib.util.spec_from_file_location("sync", Path(__file__).parent / "sync.py")
sync = importlib.util.module_from_spec(_spec)
sys.modules["sync"] = sync
_spec.loader.exec_module(sync)


# Active-set markers (used for the generic region-function tests).
ACTIVE_STEM_BEGIN = ">>> BEGIN active-set classifier"
ACTIVE_STEM_END = "<<< END active-set classifier"
BEGIN_RE = re.compile(re.escape(ACTIVE_STEM_BEGIN))
END_RE = re.compile(re.escape(ACTIVE_STEM_END))

CONSUMER_BEGIN = "# >>> BEGIN active-set classifier (generated by _shared/sync.py — do not edit) >>>"
CONSUMER_END = "# <<< END active-set classifier <<<"


def make_consumer(body: str, *, before="import os\n", after="\ndef tail():\n    pass\n") -> str:
    """Build a fake consumer script carrying the generated-by marker fence around `body`."""
    return f"{before}{CONSUMER_BEGIN}\n{body}{CONSUMER_END}\n{after}"


def _region_asset(canonical, consumers):
    return sync.RegionAsset(
        name="t-region",
        canonical=canonical,
        begin=ACTIVE_STEM_BEGIN,
        end=ACTIVE_STEM_END,
        consumers=consumers,
    )


# --- the real registered assets resolve ---------------------------------------

def test_real_assets_registered():
    region_names = {a.name for a in sync.REGION_ASSETS}
    whole_names = {a.name for a in sync.WHOLE_FILE_ASSETS}
    assert "active-set classifier" in region_names
    assert "defensive json extractor" in region_names
    assert "renderable-fence registry" in region_names
    assert "manifest_update.py" in whole_names


def test_canonical_body_renderable_fences():
    asset = next(a for a in sync.REGION_ASSETS if a.name == "renderable-fence registry")
    body = sync.canonical_region_body(asset)
    assert "RENDERABLE_FENCES = {" in body
    assert "def renderable_fence_classes" in body
    assert "def compile_checkable_fence_classes" in body
    # the registry's canonical fence classes travel inside the region body
    assert '"d2"' in body and '"csv"' in body


def test_canonical_body_active_set():
    asset = next(a for a in sync.REGION_ASSETS if a.name == "active-set classifier")
    body = sync.canonical_region_body(asset)
    assert body.startswith("GATE_TYPE")
    assert "def classify_active" in body
    assert "class ActiveSetReport" in body


def test_canonical_body_json_extractor():
    asset = next(a for a in sync.REGION_ASSETS if a.name == "defensive json extractor")
    body = sync.canonical_region_body(asset)
    assert "def _extract_first_json" in body
    assert "no balanced JSON value found in input" in body


def test_manifest_update_canonical_exists():
    asset = next(a for a in sync.WHOLE_FILE_ASSETS if a.name == "manifest_update.py")
    text = asset.canonical.read_text()
    assert "def update_manifest" in text
    assert asset.consumers, "manifest_update.py must have consumers registered"


# --- extract_region / replace_region (regex-parameterized) --------------------

def test_replace_then_extract_roundtrips():
    body = "STUFF = 1\n"
    text = make_consumer("STALE = 0\n")
    out = sync.replace_region(text, body, BEGIN_RE, END_RE)
    assert sync.extract_region(out, BEGIN_RE, END_RE) == body


def test_replace_preserves_surroundings_and_markers():
    body = "NEW = 1\n"
    text = make_consumer("OLD = 9\n")
    out = sync.replace_region(text, body, BEGIN_RE, END_RE)
    assert "import os" in out          # before
    assert "def tail" in out           # after
    assert CONSUMER_BEGIN in out       # generated-by marker retained
    assert CONSUMER_END in out
    assert "OLD = 9" not in out        # interior replaced
    assert "NEW = 1" in out


def test_generated_by_marker_present_after_replace():
    """The generated-by banner (not the canonical banner) must survive the sync."""
    out = sync.replace_region(make_consumer("OLD\n"), "X\n", BEGIN_RE, END_RE)
    assert "generated by _shared/sync.py" in out


def test_custom_marker_stem_isolated():
    """A different marker stem extracts its own region, not another asset's."""
    jbegin = re.compile(re.escape(">>> BEGIN defensive json extractor"))
    jend = re.compile(re.escape("<<< END defensive json extractor"))
    text = (
        "x\n# >>> BEGIN defensive json extractor (canonical) >>>\n"
        "PAYLOAD = 7\n# <<< END defensive json extractor (canonical) <<<\ny\n"
    )
    assert sync.extract_region(text, jbegin, jend) == "PAYLOAD = 7\n"


# --- error cases: absent / garbled fences -------------------------------------

def test_missing_markers_raises():
    with pytest.raises(sync.RegionError):
        sync.extract_region("no markers anywhere here\n", BEGIN_RE, END_RE)


def test_only_begin_marker_raises():
    with pytest.raises(sync.RegionError):
        sync.extract_region(f"{CONSUMER_BEGIN}\nbody\n", BEGIN_RE, END_RE)


def test_out_of_order_markers_raise():
    bad = f"{CONSUMER_END}\nbody\n{CONSUMER_BEGIN}\n"
    with pytest.raises(sync.RegionError):
        sync.extract_region(bad, BEGIN_RE, END_RE)


def test_duplicate_markers_raise():
    dup = f"{CONSUMER_BEGIN}\na\n{CONSUMER_END}\n{CONSUMER_BEGIN}\nb\n{CONSUMER_END}\n"
    with pytest.raises(sync.RegionError):
        sync.extract_region(dup, BEGIN_RE, END_RE)


# --- sync_region_consumer: idempotency, tamper detection ----------------------

def test_sync_region_regenerates_then_idempotent(tmp_path):
    asset = _region_asset(tmp_path / "canon.py", [])
    body = "FRESH = 1\n"
    p = tmp_path / "consumer.py"
    p.write_text(make_consumer("STALE = 0\n"))

    assert sync.sync_region_consumer(p, asset, body, check=False) is True
    assert sync.extract_region(p.read_text(), BEGIN_RE, END_RE) == body
    assert sync.sync_region_consumer(p, asset, body, check=False) is False


def test_check_detects_tampered_region(tmp_path):
    asset = _region_asset(tmp_path / "canon.py", [])
    body = "GOOD = 1\n"
    p = tmp_path / "consumer.py"
    p.write_text(make_consumer(body))            # start in sync
    assert sync.sync_region_consumer(p, asset, body, check=True) is False

    tampered = p.read_text().replace("GOOD = 1", "BAD = 1")
    p.write_text(tampered)
    assert sync.sync_region_consumer(p, asset, body, check=True) is True   # divergence reported
    assert "BAD = 1" in p.read_text()            # check mode did NOT rewrite


def test_sync_region_raises_on_unmarked_consumer(tmp_path):
    asset = _region_asset(tmp_path / "canon.py", [])
    p = tmp_path / "bare.py"
    p.write_text("import os\n# no region markers\n")
    with pytest.raises(sync.RegionError):
        sync.sync_region_consumer(p, asset, "X\n", check=False)


# --- sync_whole_file_consumer: verbatim copy ----------------------------------

def test_whole_file_regenerates_then_idempotent(tmp_path):
    body = "#!/usr/bin/env python3\nprint('hello')\n"
    p = tmp_path / "copy.py"
    p.write_text("stale\n")
    assert sync.sync_whole_file_consumer(p, body, check=False) is True
    assert p.read_text() == body                 # byte-identical
    assert sync.sync_whole_file_consumer(p, body, check=False) is False


def test_whole_file_check_detects_divergence_no_write(tmp_path):
    body = "canonical\n"
    p = tmp_path / "copy.py"
    p.write_text("drifted\n")
    assert sync.sync_whole_file_consumer(p, body, check=True) is True
    assert p.read_text() == "drifted\n"          # check mode left it untouched


def test_whole_file_in_sync_returns_false(tmp_path):
    body = "same\n"
    p = tmp_path / "copy.py"
    p.write_text(body)
    assert sync.sync_whole_file_consumer(p, body, check=True) is False


# --- main() integration (monkeypatched asset tables) --------------------------

@pytest.fixture
def fake_repo(tmp_path, monkeypatch):
    # Region asset: canonical region file + two consumers.
    region_canon = tmp_path / "region_canon.py"
    region_canon.write_text(
        f"# {ACTIVE_STEM_BEGIN} (canonical) >>>\nPAYLOAD = 42\n# {ACTIVE_STEM_END} (canonical) <<<\n"
    )
    c1 = tmp_path / "c1.py"
    c2 = tmp_path / "c2.py"
    c1.write_text(make_consumer("STALE1\n"))
    c2.write_text(make_consumer("STALE2\n"))
    region_asset = _region_asset(region_canon, [c1, c2])

    # Whole-file asset: canonical file + one consumer.
    whole_canon = tmp_path / "whole_canon.py"
    whole_canon.write_text("#!/usr/bin/env python3\nVALUE = 1\n")
    w1 = tmp_path / "w1.py"
    w1.write_text("old\n")
    whole_asset = sync.WholeFileAsset(name="t-whole", canonical=whole_canon, consumers=[w1])

    monkeypatch.setattr(sync, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(sync, "REGION_ASSETS", [region_asset])
    monkeypatch.setattr(sync, "WHOLE_FILE_ASSETS", [whole_asset])
    monkeypatch.setattr(sync, "EMITTED_ASSETS", [])  # neutralize the real Lua mirror
    return tmp_path, region_canon, c1, c2, whole_canon, w1


def test_main_check_reports_divergence_exit_1(fake_repo):
    assert sync.main(["--check"]) == 1
    _, _, c1, c2, _, w1 = fake_repo
    assert "STALE1" in c1.read_text()            # check mode left files untouched
    assert "STALE2" in c2.read_text()
    assert w1.read_text() == "old\n"


def test_main_write_then_check_clean(fake_repo):
    _, _, c1, c2, whole_canon, w1 = fake_repo
    assert sync.main([]) == 0                     # regenerate region + whole-file
    assert "PAYLOAD = 42" in c1.read_text()
    assert "PAYLOAD = 42" in c2.read_text()
    assert "STALE1" not in c1.read_text()
    assert w1.read_text() == whole_canon.read_text()   # whole-file byte-identical
    assert sync.main(["--check"]) == 0           # now clean


def test_main_unmarked_region_consumer_exit_2(fake_repo):
    _, _, c1, _, _, _ = fake_repo
    c1.write_text("import os\n# no markers\n")
    assert sync.main(["--check"]) == 2           # RegionError -> error exit


def test_main_missing_whole_file_canonical_exit_2(fake_repo, monkeypatch):
    tmp_path = fake_repo[0]
    missing = sync.WholeFileAsset(
        name="t-missing", canonical=tmp_path / "nope.py", consumers=[tmp_path / "x.py"]
    )
    monkeypatch.setattr(sync, "WHOLE_FILE_ASSETS", [missing])
    monkeypatch.setattr(sync, "REGION_ASSETS", [])
    assert sync.main(["--check"]) == 2           # canonical missing -> error exit


# --- emitted assets (generated cross-language region: Python registry -> Lua) ----

def test_emitted_asset_registered():
    names = {a.name for a in sync.EMITTED_ASSETS}
    assert "renderable-fence Lua mirror" in names


def test_emit_lua_fence_list_format():
    body = sync.emit_lua_fence_list()
    # one line, sorted class names, real registry classes present
    assert body == 'local RENDERABLE_FENCES = { "csv", "d2" }\n'


def test_blocks_lua_region_matches_emitter():
    """The committed blocks.lua region must equal the freshly emitted body."""
    asset = next(a for a in sync.EMITTED_ASSETS if a.name == "renderable-fence Lua mirror")
    current = sync.extract_region(asset.consumer.read_text(), asset.begin_re, asset.end_re)
    assert current == asset.emit()


def test_main_emitted_regenerates_then_idempotent(tmp_path, monkeypatch):
    lua = tmp_path / "blocks.lua"
    lua.write_text(
        "-- prelude\n"
        "-- >>> BEGIN renderable-fence registry (generated) >>>\n"
        'local RENDERABLE_FENCES = { "stale" }\n'
        "-- <<< END renderable-fence registry <<<\n"
        "-- tail\n"
    )
    asset = sync.EmittedRegionAsset(
        name="t-emit",
        begin=">>> BEGIN renderable-fence registry",
        end="<<< END renderable-fence registry",
        consumer=lua,
        emit=lambda: 'local RENDERABLE_FENCES = { "csv", "d2" }\n',
    )
    monkeypatch.setattr(sync, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(sync, "REGION_ASSETS", [])
    monkeypatch.setattr(sync, "WHOLE_FILE_ASSETS", [])
    monkeypatch.setattr(sync, "EMITTED_ASSETS", [asset])

    assert sync.main(["--check"]) == 1          # stale -> divergence reported
    assert "stale" in lua.read_text()           # check mode did not rewrite
    assert sync.main([]) == 0                    # regenerate
    assert 'local RENDERABLE_FENCES = { "csv", "d2" }' in lua.read_text()
    assert "stale" not in lua.read_text()
    assert "-- prelude" in lua.read_text() and "-- tail" in lua.read_text()
    assert sync.main(["--check"]) == 0          # now clean / idempotent


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
