# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "click>=8.1",
# ]
# ///
"""Manager utility for the /yf-research skill.

Scope is deliberately narrow — defensive JSON extraction (`json-get`). Preflight
(deps + installed-rule hash + the idempotent gitignore scaffold) moved to the
`yf preflight` kernel (plan-010). Research-directory and index state is managed by
index_manager.py; report/citation tooling lives in link_normalizer.py and
credibility_scorer.py.
"""

import json
import re
import sys
from pathlib import Path

import click


# >>> BEGIN defensive json extractor (generated by _shared/sync.py — edit _shared/json_extract.py) >>>
def _extract_first_json(text: str):
    """Defensively extract the first balanced JSON value from text.

    bd's --json output may carry a warning prefix and/or be a concatenated array
    (notably `bd show`/`bd list`). Strip to the first balanced {...} or [...] block
    and parse that. Raises ValueError if none parses.
    """
    open_to_close = {"{": "}", "[": "]"}
    for i, ch in enumerate(text):
        if ch in open_to_close:
            depth = 0
            in_str = False
            esc = False
            for j in range(i, len(text)):
                c = text[j]
                if in_str:
                    if esc:
                        esc = False
                    elif c == "\\":
                        esc = True
                    elif c == '"':
                        in_str = False
                    continue
                if c == '"':
                    in_str = True
                elif c in open_to_close:
                    depth += 1
                elif c in open_to_close.values():
                    depth -= 1
                    if depth == 0:
                        try:
                            return json.loads(text[i:j + 1])
                        except json.JSONDecodeError:
                            break
            # this opener didn't yield a parse; try the next one
    raise ValueError("no balanced JSON value found in input")
# <<< END defensive json extractor (generated by _shared/sync.py — edit _shared/json_extract.py) <<<


@click.group()
def cli():
    """Manager for the /yf-research skill (defensive JSON extraction)."""
    pass


@cli.command("json-get")
@click.argument("keys", nargs=-1, required=True)
def json_get(keys: tuple[str, ...]):
    """Extract a value from JSON on stdin by key path (defensive).

    Tolerates warning prefixes and concatenated/array bd output by parsing the
    first balanced JSON value. Each argument is one nesting level; a numeric key
    indexes into a list (e.g. `bd show <id> --json | research_manager.py json-get 0 metadata`).
    """
    raw = sys.stdin.read()
    try:
        data = _extract_first_json(raw)
    except ValueError as e:
        click.echo(f"ERROR: {e}", err=True)
        sys.exit(1)
    for key in keys:
        try:
            if isinstance(data, list):
                data = data[int(key)]
            else:
                data = data[key]
        except (KeyError, TypeError, IndexError, ValueError):
            click.echo(
                f"ERROR: key {key!r} not found in path {' -> '.join(keys)}",
                err=True,
            )
            sys.exit(1)
    if isinstance(data, (dict, list)):
        click.echo(json.dumps(data, indent=2))
    else:
        click.echo(data)


@cli.command("record-epic")
@click.argument("research_dir", type=click.Path(exists=True))
@click.argument("epic_id")
def record_epic(research_dir: str, epic_id: str):
    """Persist the research<->epic linkage in plan.yaml at pour (Phase 3).

    Writes/updates a top-level `epic: <id>` line in the research dir's
    `plan.yaml` — the durable resume pointer a crashed `coordinate` session reads
    to recover after the start gate is already resolved (REQ-ORCH-008).

    yf-research's data model is a flat `plan.yaml` (not yf-plan's plan.md with a
    `**Epic:**` header + phase log), so the port collapses to the single `epic:`
    key: if absent, append it; if present, replace it in place.

    Idempotent: re-running for the same epic leaves plan.yaml byte-identical (no
    duplicate `epic:` line).
    """
    plan_yaml = Path(research_dir) / "plan.yaml"
    if not plan_yaml.exists():
        click.echo("ERROR: plan.yaml not found", err=True)
        sys.exit(1)

    epic_line = f"epic: {epic_id}"
    # Matches a live `epic: <id>` line OR the commented placeholder template the
    # plan.yaml ships with (`# epic: <id>  # ...`), so the first record-epic call
    # replaces the placeholder in place rather than appending a second line.
    epic_re = re.compile(r"^#?\s*epic:")
    lines = plan_yaml.read_text().splitlines()
    new_lines: list[str] = []
    epic_written = False
    for line in lines:
        if epic_re.match(line):
            # Replace the first matching `epic:`/placeholder line in place; drop
            # any further matches (defensive de-dup → idempotent output).
            if not epic_written:
                new_lines.append(epic_line)
                epic_written = True
        else:
            new_lines.append(line)

    if not epic_written:
        # No existing/placeholder line: append the pointer at end of doc.
        if new_lines and new_lines[-1].strip() != "":
            new_lines.append(epic_line)
        else:
            # collapse onto a single trailing blank, then add the pointer
            while new_lines and new_lines[-1].strip() == "":
                new_lines.pop()
            new_lines.append(epic_line)
        epic_field = "appended"
    else:
        epic_field = "written"

    plan_yaml.write_text("\n".join(new_lines) + "\n")
    click.echo(json.dumps({
        "epic_id": epic_id,
        "epic_field": epic_field,
    }))


if __name__ == "__main__":
    cli()
