//! End-to-end aggregate-ruleset lifecycle through the real `yf` binary
//! (REQ-YF-FLOW-001/003/004). Drives `yf skills install|upgrade|remove --json`
//! against a temp `--target` and asserts the on-disk `YOSHIKO_FLOW.md`.
//!
//! The doctor/preflight verdict-parity halves of Issue 5.1's coverage (M3) live
//! as in-crate tests named with the same `flow_install_e2e` prefix
//! (`flow_install_e2e_doctor_verdict_parity` in `cmd/doctor.rs`,
//! `flow_install_e2e_preflight_verdict_parity` in `preflight.rs`) so the gate's
//! `cargo test flow_install_e2e` runs them too — they need the crate-internal
//! `check_rules`/`check_rule` entry points an integration test cannot reach.

use std::path::Path;
use std::process::Command;

use serde_json::Value;

const YF: &str = env!("CARGO_BIN_EXE_yf");

/// The seven rule-bearing skills (each ships a `protocols/*.md`).
const RULE_SKILLS: &[&str] = &[
    "yf-beads-init",
    "yf-beads-upstream",
    "yf-drift-check",
    "yf-markdown-lint",
    "yf-optimal-instructions",
    "yf-plan",
    "yf-research",
];

const RULE_PROTOCOLS: &[&str] = &[
    "BEADS_INIT.md",
    "UPSTREAM_TRACKING.md",
    "DRIFT-CHECK-TRIGGER.md",
    "MARKDOWN_LINT.md",
    "INSTRUCTIONS.md",
    "PLANS.md",
    "RESEARCH.md",
];

const BANNER: &str = "<!-- managed by yf — do not edit by hand, edit sections at your own risk -->";

fn yf_json(args: &[&str]) -> Value {
    let out = Command::new(YF).args(args).output().expect("spawn yf");
    assert!(
        out.status.success(),
        "yf {args:?} exited non-zero: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    serde_json::from_slice(&out.stdout).unwrap_or_else(|e| {
        panic!(
            "yf {args:?} did not emit JSON ({e}): {}",
            String::from_utf8_lossy(&out.stdout)
        )
    })
}

/// Protocol names (alphabetical, as they appear) parsed from a YOSHIKO_FLOW.md.
fn section_protocols(text: &str) -> Vec<String> {
    text.lines()
        .filter(|l| l.trim_start().starts_with("<!-- yf-flow:") && !l.contains(":end"))
        .filter_map(|l| {
            l.split_whitespace()
                .find_map(|t| t.strip_prefix("protocol=").map(str::to_string))
        })
        .collect()
}

#[test]
fn flow_install_e2e_lifecycle() {
    let tmp = tempfile::tempdir().unwrap();
    let target = tmp.path().join("skills");

    // 1. install all rule-bearing skills.
    let mut args = vec!["skills", "install"];
    args.extend_from_slice(RULE_SKILLS);
    args.extend_from_slice(&["--target", target.to_str().unwrap(), "--json"]);
    let j = yf_json(&args);

    let flow_file = j["flow_file"]
        .as_str()
        .expect("flow_file in JSON")
        .to_string();
    let rules_dir = j["rules_dir"]
        .as_str()
        .expect("rules_dir in JSON")
        .to_string();
    assert!(Path::new(&flow_file).is_file(), "YOSHIKO_FLOW.md written");

    let text = std::fs::read_to_string(&flow_file).unwrap();
    assert!(text.starts_with(BANNER), "banner heads the file");
    assert!(
        text.contains("<!-- generated by yf v"),
        "version generated-on note"
    );

    let protos = section_protocols(&text);
    // Every rule-bearing protocol is present...
    for p in RULE_PROTOCOLS {
        assert!(
            protos.contains(&p.to_string()),
            "section for {p} present: {protos:?}"
        );
    }
    // ...alphabetically ordered...
    let mut sorted = protos.clone();
    sorted.sort();
    assert_eq!(protos, sorted, "sections are alpha-ordered by protocol");
    // ...and NO standalone rule files exist.
    for p in RULE_PROTOCOLS {
        assert!(
            !Path::new(&rules_dir).join(p).exists(),
            "no standalone {p} — only the aggregate"
        );
    }

    // 2. upgrade is idempotent (byte-stable aggregate).
    let before = std::fs::read(&flow_file).unwrap();
    let mut up = vec!["skills", "upgrade"];
    up.extend_from_slice(RULE_SKILLS);
    up.extend_from_slice(&["--target", target.to_str().unwrap(), "--json"]);
    yf_json(&up);
    let after = std::fs::read(&flow_file).unwrap();
    assert_eq!(before, after, "upgrade is byte-stable / idempotent");

    // 3. remove ONE skill drops only its section; the file survives.
    let rm = yf_json(&[
        "skills",
        "remove",
        "yf-plan",
        "--target",
        target.to_str().unwrap(),
        "--json",
    ]);
    assert_eq!(rm["flow_deleted"], Value::Bool(false));
    let text = std::fs::read_to_string(&flow_file).unwrap();
    let protos = section_protocols(&text);
    assert!(
        !protos.contains(&"PLANS.md".to_string()),
        "PLANS.md section dropped"
    );
    assert!(
        protos.contains(&"RESEARCH.md".to_string()),
        "others retained"
    );

    // 4. remove ALL remaining rule-bearing skills deletes the file (S6).
    let mut rmall = vec!["skills", "remove"];
    rmall.extend_from_slice(RULE_SKILLS);
    rmall.extend_from_slice(&["--target", target.to_str().unwrap(), "--json"]);
    let rm = yf_json(&rmall);
    assert_eq!(
        rm["flow_deleted"],
        Value::Bool(true),
        "empty aggregate deleted"
    );
    assert!(!Path::new(&flow_file).exists(), "YOSHIKO_FLOW.md gone");
}

/// REQ-YF-FLOW-003 (M3): legacy → aggregate transition through the binary —
/// pre-seed standalone rule files (incl. for a skill not named this run), run an
/// upgrade, and assert every standalone is folded into the aggregate and deleted.
#[test]
fn flow_install_e2e_legacy_transition() {
    let tmp = tempfile::tempdir().unwrap();
    let target = tmp.path().join("skills");

    // Discover the rules dir via a dry-run (writes nothing).
    let j = yf_json(&[
        "skills",
        "install",
        "yf-plan",
        "--target",
        target.to_str().unwrap(),
        "--dry-run",
        "--json",
    ]);
    let rules_dir = std::path::PathBuf::from(j["rules_dir"].as_str().unwrap());
    std::fs::create_dir_all(&rules_dir).unwrap();

    // Pre-seed legacy standalones: PLANS.md (acted on) + RESEARCH.md (NOT acted
    // on) + a foreign BEADS.md that must survive.
    std::fs::write(rules_dir.join("PLANS.md"), b"legacy plans\n").unwrap();
    std::fs::write(rules_dir.join("RESEARCH.md"), b"legacy research\n").unwrap();
    std::fs::write(rules_dir.join("BEADS.md"), b"from bd init\n").unwrap();

    // Upgrade only yf-plan → migration folds ALL yf-owned standalones.
    yf_json(&[
        "skills",
        "upgrade",
        "yf-plan",
        "--target",
        target.to_str().unwrap(),
        "--json",
    ]);

    assert!(
        !rules_dir.join("PLANS.md").exists(),
        "PLANS.md folded + deleted"
    );
    assert!(
        !rules_dir.join("RESEARCH.md").exists(),
        "RESEARCH.md folded + deleted"
    );
    assert!(
        rules_dir.join("BEADS.md").exists(),
        "foreign BEADS.md untouched"
    );

    let text = std::fs::read_to_string(rules_dir.join("YOSHIKO_FLOW.md")).unwrap();
    let protos = section_protocols(&text);
    assert!(protos.contains(&"PLANS.md".to_string()));
    assert!(
        protos.contains(&"RESEARCH.md".to_string()),
        "non-selected standalone folded too"
    );
}
