//! The aggregated `YOSHIKO_FLOW.md` ruleset format (REQ-YF-FLOW-*).
//!
//! `yf` surfaces every rule-bearing skill's companion protocol as **one**
//! operator-facing file in the rules dir, `YOSHIKO_FLOW.md`, instead of a
//! scatter of standalone `*.md` files. This module owns that aggregate format
//! end-to-end — exactly as [`crate::marker`] owns the SKILL.md integrity marker.
//!
//! ## File shape
//!
//! ```text
//! <!-- managed by yf — do not edit by hand, edit sections at your own risk -->
//! <!-- generated by yf v0.1.0 -->
//!
//! <!-- yf-flow: skill=yf-beads-init protocol=BEADS_INIT.md version=1.0.1 sha256=<body-hash> -->
//! …protocol body verbatim…
//! <!-- yf-flow:end protocol=BEADS_INIT.md -->
//!
//! <!-- yf-flow: skill=yf-plan protocol=PLANS.md version=1.0.1 sha256=<body-hash> -->
//! …
//! <!-- yf-flow:end protocol=PLANS.md -->
//! ```
//!
//! - **Banner** — a fixed two-line header. The "generated by" line carries the
//!   `yf` semver (deterministic), **never a wall-clock timestamp**, so a
//!   re-serialize never churns bytes (REQ-YF-FLOW: generated-on determinism).
//! - **Sections** — one per protocol, ordered alphabetically by `protocol`
//!   filename for stable diffs. Each section's `sha256` is over the **section
//!   body** (the protocol file verbatim), so it equals the `manifest.json` file
//!   sha256 — doctor/preflight reuse the same hash basis.
//!
//! The banner and the generated-on note are **never** part of any section's hash
//! basis (only section bodies are hashed), so doctor/preflight verdicts are
//! immune to header churn.

// Public aggregate API consumed by the install / upgrade / remove / doctor /
// preflight paths (later beads in this plan).
#![allow(dead_code)]

use sha2::{Digest, Sha256};

/// First banner line: the do-not-edit warning.
pub const BANNER_WARNING: &str =
    "<!-- managed by yf — do not edit by hand, edit sections at your own risk -->";

/// Open-fence prefix; the full line is
/// `<!-- yf-flow: skill=… protocol=… version=… sha256=… -->`.
const FENCE_OPEN_PREFIX: &str = "<!-- yf-flow:";
/// End-fence prefix; the full line is `<!-- yf-flow:end protocol=… -->`.
const FENCE_END_PREFIX: &str = "<!-- yf-flow:end";

/// The aggregate file's basename in the rules dir.
pub const FLOW_FILENAME: &str = "YOSHIKO_FLOW.md";

/// One protocol's fenced section within `YOSHIKO_FLOW.md`.
///
/// `body` is the protocol file **verbatim** (so `section_body_sha256(body)`
/// equals the manifest file sha256). `version` is the manifest `version` for the
/// protocol when known; the two manifest-less protocols
/// (`DRIFT-CHECK-TRIGGER.md`, `MARKDOWN_LINT.md`) carry `None`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlowSection {
    /// Owning skill name (e.g. `yf-beads-init`).
    pub skill: String,
    /// Protocol filename (e.g. `BEADS_INIT.md`) — the ordering + identity key.
    pub protocol: String,
    /// Manifest version, when the skill ships a `protocols/manifest.json` entry.
    pub version: Option<String>,
    /// SHA256 of `body` (lowercase hex). Equals the manifest file sha256.
    pub sha256: String,
    /// The protocol file body, verbatim (newline-terminated).
    pub body: String,
}

impl FlowSection {
    /// Build a section from a skill, protocol, optional version, and verbatim
    /// body, computing `sha256` over the body.
    pub fn new(
        skill: impl Into<String>,
        protocol: impl Into<String>,
        version: Option<String>,
        body: impl Into<String>,
    ) -> Self {
        let body = body.into();
        let sha256 = section_body_sha256(body.as_bytes());
        FlowSection {
            skill: skill.into(),
            protocol: protocol.into(),
            version,
            sha256,
            body,
        }
    }
}

/// SHA256 (lowercase hex) over a section body. Because a body is the protocol
/// file verbatim, this equals the file's `manifest.json` sha256.
pub fn section_body_sha256(body: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(body);
    let digest = h.finalize();
    let mut s = String::with_capacity(64);
    for b in digest {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// Insert or replace a section in `sections`, keyed on `protocol`. Idempotent:
/// re-upserting the same protocol replaces the existing section in place (no
/// duplicate). The vector is kept sorted alphabetically by `protocol` so callers
/// never depend on insertion order (REQ-YF-FLOW: deterministic ordering).
pub fn upsert_section(sections: &mut Vec<FlowSection>, section: FlowSection) {
    match sections.iter_mut().find(|s| s.protocol == section.protocol) {
        Some(existing) => *existing = section,
        None => sections.push(section),
    }
    sections.sort_by(|a, b| a.protocol.cmp(&b.protocol));
}

/// Remove the section for `protocol`, returning `true` if one was removed.
/// Removing an absent protocol is a no-op returning `false` (idempotent).
pub fn remove_section(sections: &mut Vec<FlowSection>, protocol: &str) -> bool {
    let before = sections.len();
    sections.retain(|s| s.protocol != protocol);
    sections.len() != before
}

/// Reconcile `sections` against the set of `(skill, protocol)` pairs that are
/// **embedded and valid** — present in the binary's skill tree AND not
/// `deprecated:true` in their `manifest.json`.
///
/// Returns `(kept, pruned)`. A section is **pruned** when its `(skill, protocol)`
/// is absent from `embedded_valid` — i.e. the protocol is no longer embedded, or
/// the skill was renamed/removed, or the manifest marked it deprecated. A section
/// is **kept** purely because it is still embedded-and-valid; reconcile keys on
/// the embedded set, **never** on whatever skills a given invocation selected, so
/// a protocol for a skill simply not named this run is retained (R2).
pub fn reconcile(
    sections: Vec<FlowSection>,
    embedded_valid: &std::collections::BTreeSet<(String, String)>,
) -> (Vec<FlowSection>, Vec<FlowSection>) {
    let mut kept = Vec::new();
    let mut pruned = Vec::new();
    for s in sections {
        let key = (s.skill.clone(), s.protocol.clone());
        if embedded_valid.contains(&key) {
            kept.push(s);
        } else {
            pruned.push(s);
        }
    }
    (kept, pruned)
}

/// Parse a `YOSHIKO_FLOW.md` text into its ordered sections.
///
/// Tolerant of a missing or garbled banner: sections are recovered purely from
/// their fences, so a hand-mangled header never loses content. An open fence
/// with no matching end fence is dropped (incomplete section). Returns sections
/// in file order (callers that need canonical order call [`serialize`], which
/// sorts).
pub fn parse(text: &str) -> Vec<FlowSection> {
    let mut out = Vec::new();
    let mut lines = text.split_inclusive('\n').peekable();

    while let Some(seg) = lines.next() {
        let line = seg.strip_suffix('\n').unwrap_or(seg);
        let trimmed = line.trim_start();
        // An open fence is `<!-- yf-flow:` but NOT `<!-- yf-flow:end`.
        if !trimmed.starts_with(FENCE_OPEN_PREFIX) || trimmed.starts_with(FENCE_END_PREFIX) {
            continue;
        }
        let Some(attrs) = parse_open_fence(trimmed) else {
            continue;
        };
        // Collect body lines verbatim until the matching end fence.
        let mut body = String::new();
        let mut closed = false;
        for seg in lines.by_ref() {
            let line = seg.strip_suffix('\n').unwrap_or(seg);
            let t = line.trim_start();
            if t.starts_with(FENCE_END_PREFIX) {
                // Match on protocol so nested/mismatched fences are tolerated.
                if end_fence_protocol(t).as_deref() == Some(attrs.protocol.as_str()) {
                    closed = true;
                    break;
                }
            }
            body.push_str(seg);
        }
        if !closed {
            // No end fence: incomplete section, drop it.
            continue;
        }
        out.push(FlowSection {
            skill: attrs.skill,
            protocol: attrs.protocol,
            version: attrs.version,
            sha256: attrs.sha256,
            body,
        });
    }
    out
}

/// Serialize sections into a complete `YOSHIKO_FLOW.md` text: banner, the
/// `yf`-version generated-on note, then one fenced section per protocol ordered
/// alphabetically by `protocol`. `yf_version` is the deterministic version
/// stamp (never a timestamp), so re-serializing the same sections is
/// byte-stable.
pub fn serialize(sections: &[FlowSection], yf_version: &str) -> String {
    let mut ordered: Vec<&FlowSection> = sections.iter().collect();
    ordered.sort_by(|a, b| a.protocol.cmp(&b.protocol));

    let mut out = String::new();
    out.push_str(BANNER_WARNING);
    out.push('\n');
    out.push_str(&format!("<!-- generated by yf v{yf_version} -->\n"));

    for s in ordered {
        out.push('\n');
        out.push_str(&open_fence(s));
        out.push('\n');
        out.push_str(&s.body);
        // Bodies are newline-terminated (protocol files are); guarantee the end
        // fence lands on its own line even for a body that is not.
        if !s.body.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&end_fence(&s.protocol));
        out.push('\n');
    }
    out
}

/// Build the open-fence line (no trailing newline). `version` is omitted from
/// the line when `None` (manifest-less protocols).
fn open_fence(s: &FlowSection) -> String {
    match &s.version {
        Some(v) => format!(
            "{FENCE_OPEN_PREFIX} skill={} protocol={} version={} sha256={} -->",
            s.skill, s.protocol, v, s.sha256
        ),
        None => format!(
            "{FENCE_OPEN_PREFIX} skill={} protocol={} sha256={} -->",
            s.skill, s.protocol, s.sha256
        ),
    }
}

/// Build the end-fence line (no trailing newline).
fn end_fence(protocol: &str) -> String {
    format!("{FENCE_END_PREFIX} protocol={protocol} -->")
}

/// Parsed attributes of an open fence.
struct OpenAttrs {
    skill: String,
    protocol: String,
    version: Option<String>,
    sha256: String,
}

/// Parse an open-fence line's `key=value` attributes. Requires `skill`,
/// `protocol`, and `sha256`; `version` is optional. Returns `None` if a required
/// attribute is missing.
fn parse_open_fence(line: &str) -> Option<OpenAttrs> {
    let body = line.strip_prefix(FENCE_OPEN_PREFIX)?;
    let body = body.strip_suffix("-->").unwrap_or(body).trim();
    let mut skill = None;
    let mut protocol = None;
    let mut version = None;
    let mut sha256 = None;
    for tok in body.split_whitespace() {
        if let Some(v) = tok.strip_prefix("skill=") {
            skill = Some(v.to_string());
        } else if let Some(v) = tok.strip_prefix("protocol=") {
            protocol = Some(v.to_string());
        } else if let Some(v) = tok.strip_prefix("version=") {
            version = Some(v.to_string());
        } else if let Some(v) = tok.strip_prefix("sha256=") {
            sha256 = Some(v.to_string());
        }
    }
    Some(OpenAttrs {
        skill: skill?,
        protocol: protocol?,
        version,
        sha256: sha256?,
    })
}

/// Extract `protocol=…` from an end-fence line.
fn end_fence_protocol(line: &str) -> Option<String> {
    let body = line.strip_prefix(FENCE_END_PREFIX)?;
    let body = body.strip_suffix("-->").unwrap_or(body).trim();
    body.split_whitespace()
        .find_map(|tok| tok.strip_prefix("protocol=").map(str::to_string))
}

#[cfg(test)]
mod tests {
    use super::*;

    const VER: &str = "0.1.0";

    fn sec(skill: &str, protocol: &str, version: Option<&str>, body: &str) -> FlowSection {
        FlowSection::new(skill, protocol, version.map(str::to_string), body)
    }

    // REQ-YF-FLOW-001: a serialized file carries the banner and the deterministic
    // generated-on note (version, not a timestamp).
    #[test]
    fn serialize_emits_banner_and_version_note() {
        let s = sec("yf-plan", "PLANS.md", Some("1.0.1"), "rule body\n");
        let text = serialize(&[s], VER);
        assert!(text.starts_with(BANNER_WARNING));
        assert!(text.contains("<!-- generated by yf v0.1.0 -->"));
        // No wall-clock date tokens.
        assert!(!text.contains("generated on"));
    }

    // REQ-YF-FLOW: round-trip — parse(serialize(x)) preserves bodies, order key,
    // skill, version, and sha.
    #[test]
    fn round_trip_preserves_sections() {
        let a = sec(
            "yf-beads-init",
            "BEADS_INIT.md",
            Some("1.0.1"),
            "alpha body\n",
        );
        let b = sec("yf-plan", "PLANS.md", Some("1.0.1"), "plan body\nline2\n");
        let text = serialize(&[a.clone(), b.clone()], VER);
        let parsed = parse(&text);
        assert_eq!(parsed.len(), 2);
        // Serialized alpha-by-protocol: BEADS_INIT.md before PLANS.md.
        assert_eq!(parsed[0], a);
        assert_eq!(parsed[1], b);
    }

    // REQ-YF-FLOW: sections are ordered alphabetically by protocol regardless of
    // input order (stable diffs).
    #[test]
    fn serialize_orders_alpha_by_protocol() {
        let z = sec("yf-research", "RESEARCH.md", Some("1.0.3"), "z\n");
        let a = sec("yf-beads-init", "BEADS_INIT.md", Some("1.0.1"), "a\n");
        let text = serialize(&[z, a], VER);
        let i_a = text.find("protocol=BEADS_INIT.md").unwrap();
        let i_z = text.find("protocol=RESEARCH.md").unwrap();
        assert!(i_a < i_z, "BEADS_INIT.md must precede RESEARCH.md");
    }

    // REQ-YF-FLOW: a manifest-less protocol (no version) round-trips with version
    // omitted from the fence and parsed back as None.
    #[test]
    fn version_optional_round_trips_as_none() {
        let s = sec(
            "yf-drift-check",
            "DRIFT-CHECK-TRIGGER.md",
            None,
            "drift body\n",
        );
        let text = serialize(std::slice::from_ref(&s), VER);
        assert!(
            !text.contains("version="),
            "no version token expected: {text}"
        );
        let parsed = parse(&text);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0], s);
        assert_eq!(parsed[0].version, None);
    }

    // REQ-YF-FLOW: the section sha256 equals a plain sha256 over the verbatim
    // body (so it matches manifest.json file sha256).
    #[test]
    fn section_sha_matches_body_hash() {
        let body = "exact protocol bytes\n";
        let s = sec("yf-plan", "PLANS.md", Some("1.0.1"), body);
        assert_eq!(s.sha256, section_body_sha256(body.as_bytes()));
        assert_eq!(s.sha256.len(), 64);
    }

    // REQ-YF-FLOW: parse is tolerant of a missing/garbled banner — sections are
    // recovered from fences alone.
    #[test]
    fn parse_tolerates_garbled_banner() {
        let s = sec("yf-plan", "PLANS.md", Some("1.0.1"), "body\n");
        let good = serialize(std::slice::from_ref(&s), VER);
        // Replace the banner with garbage; keep the fenced section.
        let section_start = good.find(FENCE_OPEN_PREFIX).unwrap();
        let mangled = format!("garbage header line\n\n{}", &good[section_start..]);
        let parsed = parse(&mangled);
        assert_eq!(parsed, vec![s]);
    }

    // REQ-YF-FLOW: an open fence with no matching end fence is dropped.
    #[test]
    fn parse_drops_unterminated_section() {
        let text = format!(
            "{BANNER_WARNING}\n\n{FENCE_OPEN_PREFIX} skill=yf-plan protocol=PLANS.md \
             version=1.0.1 sha256=abc -->\nbody with no end fence\n"
        );
        assert!(parse(&text).is_empty());
    }

    // REQ-YF-FLOW: serialize → serialize is byte-stable (no timestamp churn).
    #[test]
    fn serialize_is_byte_stable() {
        let s = sec("yf-plan", "PLANS.md", Some("1.0.1"), "body\n");
        let once = serialize(std::slice::from_ref(&s), VER);
        let parsed = parse(&once);
        let twice = serialize(&parsed, VER);
        assert_eq!(once, twice);
    }

    // --- 1.2: upsert / remove ------------------------------------------------

    // REQ-YF-FLOW: upsert adds a new section and keeps the vector alpha-sorted.
    #[test]
    fn upsert_adds_and_sorts() {
        let mut v = vec![sec("yf-research", "RESEARCH.md", Some("1.0.3"), "r\n")];
        upsert_section(
            &mut v,
            sec("yf-beads-init", "BEADS_INIT.md", Some("1.0.1"), "b\n"),
        );
        assert_eq!(v.len(), 2);
        assert_eq!(v[0].protocol, "BEADS_INIT.md");
        assert_eq!(v[1].protocol, "RESEARCH.md");
    }

    // REQ-YF-FLOW: re-upserting the same protocol REPLACES in place (no dup).
    #[test]
    fn upsert_is_replace_not_duplicate() {
        let mut v = vec![sec("yf-plan", "PLANS.md", Some("1.0.0"), "old\n")];
        upsert_section(&mut v, sec("yf-plan", "PLANS.md", Some("1.0.1"), "new\n"));
        assert_eq!(v.len(), 1);
        assert_eq!(v[0].version.as_deref(), Some("1.0.1"));
        assert_eq!(v[0].body, "new\n");
    }

    // REQ-YF-FLOW: remove drops the named section; removing a missing one is a
    // no-op returning false.
    #[test]
    fn remove_present_and_missing() {
        let mut v = vec![
            sec("yf-plan", "PLANS.md", Some("1.0.1"), "p\n"),
            sec("yf-research", "RESEARCH.md", Some("1.0.3"), "r\n"),
        ];
        assert!(remove_section(&mut v, "PLANS.md"));
        assert_eq!(v.len(), 1);
        assert!(
            !remove_section(&mut v, "PLANS.md"),
            "remove-missing is a no-op"
        );
        assert_eq!(v.len(), 1);
    }

    // --- 1.3: reconcile ------------------------------------------------------

    fn valid_set(pairs: &[(&str, &str)]) -> std::collections::BTreeSet<(String, String)> {
        pairs
            .iter()
            .map(|(s, p)| (s.to_string(), p.to_string()))
            .collect()
    }

    // REQ-YF-FLOW-002: reconcile prunes a section whose protocol is no longer
    // embedded (skill removed / protocol gone).
    #[test]
    fn reconcile_prunes_not_embedded() {
        let sections = vec![
            sec("yf-plan", "PLANS.md", Some("1.0.1"), "p\n"),
            sec("yf-gone", "GONE.md", Some("1.0.0"), "g\n"),
        ];
        let valid = valid_set(&[("yf-plan", "PLANS.md")]);
        let (kept, pruned) = reconcile(sections, &valid);
        assert_eq!(
            kept.iter().map(|s| &s.protocol).collect::<Vec<_>>(),
            vec!["PLANS.md"]
        );
        assert_eq!(
            pruned.iter().map(|s| &s.protocol).collect::<Vec<_>>(),
            vec!["GONE.md"]
        );
    }

    // REQ-YF-FLOW: reconcile prunes a deprecated protocol (absent from the valid
    // set the caller built by excluding deprecated entries).
    #[test]
    fn reconcile_prunes_deprecated() {
        let sections = vec![sec("yf-plan", "PLANS.md", Some("1.0.1"), "p\n")];
        // Caller excludes PLANS.md from the valid set because it is deprecated.
        let valid = valid_set(&[]);
        let (kept, pruned) = reconcile(sections, &valid);
        assert!(kept.is_empty());
        assert_eq!(pruned.len(), 1);
    }

    // REQ-YF-FLOW (R2): reconcile KEEPS a section for a skill merely not selected
    // this invocation — it keys on the embedded set, never the selection.
    #[test]
    fn reconcile_keeps_unselected_but_embedded() {
        let sections = vec![
            sec("yf-plan", "PLANS.md", Some("1.0.1"), "p\n"),
            sec("yf-research", "RESEARCH.md", Some("1.0.3"), "r\n"),
        ];
        // Both still embedded-and-valid even though only yf-plan was "selected".
        let valid = valid_set(&[("yf-plan", "PLANS.md"), ("yf-research", "RESEARCH.md")]);
        let (kept, pruned) = reconcile(sections, &valid);
        assert_eq!(kept.len(), 2);
        assert!(pruned.is_empty());
    }

    // --- 1.4: generated-on hash determinism ----------------------------------

    // REQ-YF-FLOW-006 (R3): serialize→parse→serialize is hash-stable — the
    // generated-on note (yf version, not a timestamp) never perturbs bytes, and
    // section sha256 is over the body only.
    #[test]
    fn generated_on_is_hash_stable() {
        let sections = vec![
            sec("yf-beads-init", "BEADS_INIT.md", Some("1.0.1"), "alpha\n"),
            sec("yf-plan", "PLANS.md", Some("1.0.1"), "beta\nmore\n"),
        ];
        let s1 = serialize(&sections, VER);
        let s2 = serialize(&parse(&s1), VER);
        let s3 = serialize(&parse(&s2), VER);
        assert_eq!(s1, s2, "re-serialize must be byte-identical");
        assert_eq!(s2, s3, "and stable across repeated round-trips");
        // Section shas are unchanged by the header.
        for s in parse(&s3) {
            assert_eq!(s.sha256, section_body_sha256(s.body.as_bytes()));
        }
    }
}
