-- Render "renderable" markdown fences to PDF at pandoc time, so the Markdown
-- source stays pure GFM (a ```d2``` diagram / ```csv``` table travels inline and
-- is rendered here, not committed as a standalone image).
--
--   d2  -> shell `d2 <in> <out>.pdf`, embed the PDF as a pandoc.Image (vector,
--          sharper + smaller than PNG; absolute temp path so pandoc resolves it
--          independent of --resource-path).
--   csv -> pandoc.read(text, "csv").blocks — a native LaTeX table, no extra tool.
--
-- Both renderers `pcall`-degrade: on any failure (bad source, or the `d2` binary
-- absent) the fence is LEFT verbatim as a code listing and the build still exits 0
-- (the degrade-to-code contract). Exec is arg-vector only (`pandoc.pipe`) — never a
-- shell string with concatenated paths.
--
-- Temp lifecycle: a rendered d2 PDF must OUTLIVE this filter pass — xelatex embeds
-- it after every Lua filter has run — so a per-block auto-cleaned temp dir cannot
-- hold it. md2pdf.py owns one run-scoped temp dir (passed via MD2PDF_FENCE_TMPDIR)
-- and reaps it in its `finally` AFTER pandoc completes, so there is no leak. Run
-- standalone (no env var) the filter creates its own dir under $TMPDIR and leaves
-- it for the OS to reap.

-- The set of renderable fence classes is GENERATED from the canonical
-- `_shared/renderable_fences.py` registry by `_shared/sync.py` (Python->Lua
-- emitter) and held byte-stable by a DRIFT-CHECK `field-set-equal` edge — do not
-- hand-edit the region body.
-- >>> BEGIN renderable-fence registry (generated by _shared/sync.py — do not edit) >>>
local RENDERABLE_FENCES = { "csv", "d2" }
-- <<< END renderable-fence registry <<<

local function is_renderable(cls)
  for _, c in ipairs(RENDERABLE_FENCES) do
    if c == cls then
      return true
    end
  end
  return false
end

-- Run-scoped render dir for d2 output. Reused across blocks; lazily resolved.
local render_dir = os.getenv("MD2PDF_FENCE_TMPDIR")
local counter = 0

local function ensure_render_dir()
  if render_dir then
    return render_dir
  end
  -- Standalone fallback (no md2pdf.py reaper): a unique dir under the system temp,
  -- left for the OS to reap. The md2pdf path always sets MD2PDF_FENCE_TMPDIR.
  local base = os.getenv("TMPDIR") or "/tmp"
  render_dir = pandoc.path.join({ base, "md2pdf-fence-" .. tostring(os.time()) .. "-" .. tostring(os.clock()) })
  pandoc.system.make_directory(render_dir, true)
  return render_dir
end

local function render_d2(block)
  local dir = ensure_render_dir()
  counter = counter + 1
  local stem = pandoc.path.join({ dir, "d2-" .. tostring(counter) })
  local infile = stem .. ".d2"
  local outfile = stem .. ".pdf"

  local fh = io.open(infile, "w")
  if not fh then
    return nil -- cannot stage source -> degrade to verbatim listing
  end
  fh:write(block.text)
  fh:close()

  -- Arg-vector exec (no shell). pandoc.pipe raises on non-zero exit or a missing
  -- `d2` binary; pcall turns either into a clean degrade.
  local ok = pcall(function()
    pandoc.pipe("d2", { infile, outfile }, "")
  end)
  if not ok then
    return nil
  end
  -- Absolute path: pandoc resolves it regardless of --resource-path (E1 finding).
  return pandoc.Para({ pandoc.Image({}, outfile) })
end

local function render_csv(block)
  local ok, doc = pcall(pandoc.read, block.text, "csv")
  if not ok or not doc then
    return nil -- malformed csv -> degrade to verbatim listing
  end
  return doc.blocks
end

function CodeBlock(block)
  local cls = block.classes[1]
  if not cls or not is_renderable(cls) then
    return nil -- not a renderable fence: leave untouched
  end
  if cls == "d2" then
    return render_d2(block)
  elseif cls == "csv" then
    return render_csv(block)
  end
  return nil
end
